version: '3.7'

services:

  frontend:
    build: contactos
    ports: 
      - 3000:3000
    volumes:
      - build_folder:/frontend/build
  
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
    depends_on:
      - frontend

volumes:
  build_folder: