const Types = {
    CONTACTOS_LOADING: "CONTACTOS_LOADING",
    GET_CONTACTOS:"GET_CONTACTOS",
    GET_CONTACTO:"GET_CONTACTO",
    DELETE_CONTACTO:"DELETE_CONTACTO",
    CREATE_CONTACTO:"CREATE_CONTACTO"
};

export default Types